### PR TITLE
added serach input as default

### PR DESCRIPTION
**Pull request by tiansijie**

### CODE REVIEW

**Comment by rovolution** [comment]
__1)__ What if the user does not want to see the search box? Should we have a prop that configures whether or not to display the search box?

__2)__ Remember to update the `headerContent` section of the README with an explanation of how there is a default search input if the user does not specify one.

__3)__ Tests! :)

**Comment by rovolution** [comment]
also, toss a screenshot in here with the new UI change

**Comment by tiansijie** [comment]
@rovolution updated

**Comment by rovolution** [comment]
@tiansijie this looks good to me! feel free to merge

**Pull request merged**
