### PR TITLE
Convert custom component string

### PR DESCRIPTION
**Pull request by jamesoh**
@tiansijie 
The project I am currently working on involves a React/Redux front-end powered by a Ruby on Rails backend. The data for the infinity menu is being served by the Rails server as json, which led to the problem of `customComponent` having to be a component. I am proposing a solution that allows for both a `String` and a `React.Component` type. For usage, this would have to be passed to the `<InfinityMenu />` component:

```
// Data can now set the customComponent field to be a string (a JSON payload in my example)
[
   {
       name: "menu1",
        id: 1,
        isOpen: true,
        customComponent: "MyComponent1"
   },
  {
       name: "menu2",
        id: 2,
        isOpen: true,
        customComponent: "MyComponent2"
   }
];

// Define your mappings
var myComponentMappings = {
    "MyComponent1": MyComponent1, 
    "MyComponent2": MyComponent2 
}

<InfinityMenu customComponentMappings={ customComponentMappings } />
```

Please let me know what you guys think and if this is an acceptable solution. I think I may be exploring optimizing search and implementing drag and drop as well if you guys are at all interested in integrating such features. Thanks for taking the time to look over.

### CODE REVIEW

**Comment by tiansijie** [comment]
@jamesoh nice PR! I love it. Just one thing, could you try to add test for this? Thanks!

**Comment by jamesoh** [comment]
Yea for sure, i'll give it a shot and update the PR!

**Comment by jamesoh** [comment]
@tiansijie how does the test look?

**Comment by tiansijie** [comment]
Looks good to me!

**Pull request merged**
