### PR TITLE
remove should component update for search mode update

### PR DESCRIPTION
**Pull request by tiansijie**

### CODE REVIEW

**Comment by tiansijie** [comment]
letting the tree get update in search mode
https://github.com/socialtables/react-infinity-menu/issues/31

**Comment by conorhastings** [comment]
@tiansijie should we allow user to pass in a custom shouldComponentUpdate so performance conscious apps that don't need update in search mode can still take advantage?

**Comment by tiansijie** [comment]
@conorhastings updated

**Comment by conorhastings** [comment]
@tiansijie looks good, please add a test and it should be ready to go

```js
function shouldComponentUpdate(currProps, currState, nextProps, nextState) {
  return nextProps.hasTest === true;
}
```

**Comment by tiansijie** [comment]
@conorhastings updated

**Comment by conorhastings** [comment]
looks good! you can bump version.

**Pull request merged**
